fixtures:
  symlinks:
    cloudwatchlogs: '#{source_dir}'
  forge_modules:
    wget:
      repo: "maestrodev/wget"
      ref: "1.7.3"
    concat:
      repo: "puppetlabs/concat"
      ref: "1.2.5"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.25.0"
