fixtures:
  symlinks:
    cloudwatchlogs: '#{source_dir}'
  forge_modules:
    wget: "maestrodev/wget"
    concat: "puppetlabs/concat"
    stdlib: "puppetlabs/stdlib"
    augeasproviders_shellvar: "herculesteam/augeasproviders_shellvar"
    augeasproviders_code: "herculesteam/augeasproviders_core"
